### PR TITLE
Example of ArrayShape for parameters

### PR DESCRIPTION
**Pull request by adaamz**

### CODE REVIEW

**Comment by wbars** [comment]
Screen Shot 2020-12-03 at 19 11 47
Please clarify what support you're missing, it's generally implemented.

**Comment by adaamz** [comment]
Nice, so that means it's only not documented. I will add it to this PR.

**Comment by adaamz** [comment]
@wbars WDYT? 🙂

**Comment by wbars** [comment]
Information about attributes applicability specified in [their declarations](https://github.com/JetBrains/phpstorm-attributes/blob/0b39907a51c663d400bfa20568bd1a58c77b2770/src/ArrayShape.php#L18) so It seems such change only duplicates this information. Thank you for the idea anyway.

**Comment by adaamz** [comment]
Would be nice if we have some example anyway. It is new thing and not much examples could be found on the web. Also official blog/repo doesn't mention it...

**Pull request closed without merging**
