### PR TITLE
Adjusting attributes to 2021.1

### PR DESCRIPTION
**Pull request by krzysztofrewak**
There were some minor changes in [the main repository](https://github.com/JetBrains/phpstorm-stubs/releases/tag/v2021.1), so I updated them here. 

I also added PHP-CS-Fixer as in main repository. I saw that you're using "curly brace in the same line as class name" convention (even with some custom made [fixer](https://github.com/JetBrains/phpstorm-stubs/blob/master/tests/CodeStyle/BracesOneLineFixer.php)), but it's against PSR-12, so I just left default codestyle configuration. If you want, I can copypaste braces fixer and apply it here.

### CODE REVIEW

**Comment by krzysztofrewak** [comment]
Also, if CS Fixer would be accepted and added to the project, I could also provide simple Github Actions configuration to run it for every pull request.

**Comment by krzysztofrewak** [comment]
@wbars, could you look at it?

**Comment by wbars** [comment]
Hey, thanks for the contribution. I'll accept delta with 2021.1, but CS Fixer and github actions are out of scope of this repo, can you please detach them?

**Comment by krzysztofrewak** [comment]
> Hey, thanks for the contribution. I'll accept delta with 2021.1, but CS Fixer and github actions are out of scope of this repo, can you please detach them?

Voila.

**Pull request merged**
